---
"____EXAMPLE____000": "=begin comment\n\n=head2 Uml Diagram\n![](plantuml/….svg)\n\n=end comment\n"
"____EXAMPLE____001": "=begin comment\n\n=head2 Example\n# Example use of module Gnome::Gtk4::ApplicationWindow\n\n=end comment\n"
"____EXAMPLE____002": "=begin comment\n\n=head2 Example\n# Example for new-applicationwindow\n\n=end comment\n"
"____EXAMPLE____003": "=begin comment\n\n=head2 Example\n# Example for get-help-overlay\n\n=end comment\n"
"____EXAMPLE____004": "=begin comment\n\n=head2 Example\n# Example for get-id\n\n=end comment\n"
"____EXAMPLE____005": "=begin comment\n\n=head2 Example\n# Example for get-show-menubar\n\n=end comment\n"
"____EXAMPLE____006": "=begin comment\n\n=head2 Example\n# Example for set-help-overlay\n\n=end comment\n"
"____EXAMPLE____007": "=begin comment\n\n=head2 Example\n# Example for set-show-menubar\n\n=end comment\n"
"____EXAMPLE____008": |
  =begin code
  my Gnome::Gtk4::Application $app .= new-application( "org.gtk.test", 0);
  my Gnome::Gtk4::Builder $builder .= from-string( q:to/EOUI/, -1);
    <interface>
      <menu id='menubar'>
        <submenu>
          <attribute name='label' translatable='yes'>_Edit</attribute>
          <item>
            <attribute name='label' translatable='yes'>_Copy</attribute>
            <attribute name='action'>win.copy</attribute>
          </item>
          <item>
            <attribute name='label' translatable='yes'>_Paste</attribute>
            <attribute name='action'>win.paste</attribute>
          </item>
        </submenu>
      </menu>
    </interface>
    EOUI

  my Gnome::Gio::MenuModel $menubar = $builder.get-object("menubar);
  $app.set-menubar($menubar);
  $builder.clear-object
  
  # ...
  my Gnome::Gtk4::Widget $window .= new-application-window($app);
  =end code
...