---
"____EXAMPLE____000": "=begin comment\n\n=head2 Uml Diagram\n![](plantuml/….svg)\n\n=end comment\n"
"____EXAMPLE____001": "=begin comment\n\n=head2 Example\n# Example use of module Gnome::Gio::Application\n\n=end comment\n"
"____EXAMPLE____002": "=begin comment\n\n=head2 Example\n# Example for new-application\n\n=end comment\n"
"____EXAMPLE____003": "=begin comment\n\n=head2 Example\n# Example for activate\n\n=end comment\n"
"____EXAMPLE____004": "=begin comment\n\n=head2 Example\n# Example for add-main-option\n\n=end comment\n"
"____EXAMPLE____005": "=begin comment\n\n=head2 Example\n# Example for add-main-option-entries\n\n=end comment\n"
"____EXAMPLE____006": "=begin comment\n\n=head2 Example\n# Example for add-option-group\n\n=end comment\n"
"____EXAMPLE____007": "=begin comment\n\n=head2 Example\n# Example for bind-busy-property\n\n=end comment\n"
"____EXAMPLE____008": "=begin comment\n\n=head2 Example\n# Example for get-application-id\n\n=end comment\n"
"____EXAMPLE____009": "=begin comment\n\n=head2 Example\n# Example for get-dbus-connection\n\n=end comment\n"
"____EXAMPLE____010": "=begin comment\n\n=head2 Example\n# Example for get-dbus-object-path\n\n=end comment\n"
"____EXAMPLE____011": "=begin comment\n\n=head2 Example\n# Example for get-flags\n\n=end comment\n"
"____EXAMPLE____012": "=begin comment\n\n=head2 Example\n# Example for get-inactivity-timeout\n\n=end comment\n"
"____EXAMPLE____013": "=begin comment\n\n=head2 Example\n# Example for get-is-busy\n\n=end comment\n"
"____EXAMPLE____014": "=begin comment\n\n=head2 Example\n# Example for get-is-registered\n\n=end comment\n"
"____EXAMPLE____015": "=begin comment\n\n=head2 Example\n# Example for get-is-remote\n\n=end comment\n"
"____EXAMPLE____016": "=begin comment\n\n=head2 Example\n# Example for get-resource-base-path\n\n=end comment\n"
"____EXAMPLE____017": "=begin comment\n\n=head2 Example\n# Example for hold\n\n=end comment\n"
"____EXAMPLE____018": "=begin comment\n\n=head2 Example\n# Example for mark-busy\n\n=end comment\n"
"____EXAMPLE____019": "=begin comment\n\n=head2 Example\n# Example for open\n\n=end comment\n"
"____EXAMPLE____020": "=begin comment\n\n=head2 Example\n# Example for quit\n\n=end comment\n"
"____EXAMPLE____021": "=begin comment\n\n=head2 Example\n# Example for register\n\n=end comment\n"
"____EXAMPLE____022": "=begin comment\n\n=head2 Example\n# Example for release\n\n=end comment\n"
"____EXAMPLE____023": "=begin comment\n\n=head2 Example\n# Example for run\n\n=end comment\n"
"____EXAMPLE____024": "=begin comment\n\n=head2 Example\n# Example for send-notification\n\n=end comment\n"
"____EXAMPLE____025": "=begin comment\n\n=head2 Example\n# Example for set-application-id\n\n=end comment\n"
"____EXAMPLE____026": "=begin comment\n\n=head2 Example\n# Example for set-default\n\n=end comment\n"
"____EXAMPLE____027": "=begin comment\n\n=head2 Example\n# Example for set-flags\n\n=end comment\n"
"____EXAMPLE____028": "=begin comment\n\n=head2 Example\n# Example for set-inactivity-timeout\n\n=end comment\n"
"____EXAMPLE____029": "=begin comment\n\n=head2 Example\n# Example for set-option-context-description\n\n=end comment\n"
"____EXAMPLE____030": "=begin comment\n\n=head2 Example\n# Example for set-option-context-parameter-string\n\n=end comment\n"
"____EXAMPLE____031": "=begin comment\n\n=head2 Example\n# Example for set-option-context-summary\n\n=end comment\n"
"____EXAMPLE____032": "=begin comment\n\n=head2 Example\n# Example for set-resource-base-path\n\n=end comment\n"
"____EXAMPLE____033": "=begin comment\n\n=head2 Example\n# Example for unbind-busy-property\n\n=end comment\n"
"____EXAMPLE____034": "=begin comment\n\n=head2 Example\n# Example for unmark-busy\n\n=end comment\n"
"____EXAMPLE____035": "=begin comment\n\n=head2 Example\n# Example for withdraw-notification\n\n=end comment\n"
"____EXAMPLE____036": "=begin comment\n\n=head2 Example\n# Example for get-default\n\n=end comment\n"
"____EXAMPLE____037": "=begin comment\n\n=head2 Example\n# Example for id-is-valid\n\n=end comment\n"
"____EXAMPLE____038": "=begin comment\n\n=head2 Example\n# Example for signal activate\n\n=end comment\n"
"____EXAMPLE____039": "=begin comment\n\n=head2 Example\n# Example for signal command-line\n\n=end comment\n"
"____EXAMPLE____040": "=begin comment\n\n=head2 Example\n# Example for signal handle-local-options\n\n=end comment\n"
"____EXAMPLE____041": "=begin comment\n\n=head2 Example\n# Example for signal name-lost\n\n=end comment\n"
"____EXAMPLE____042": "=begin comment\n\n=head2 Example\n# Example for signal open\n\n=end comment\n"
"____EXAMPLE____043": "=begin comment\n\n=head2 Example\n# Example for signal shutdown\n\n=end comment\n"
"____EXAMPLE____044": "=begin comment\n\n=head2 Example\n# Example for signal startup\n\n=end comment\n"
...