=comment Package: Gio, C-Source: ioenums
use v6.d;
#-------------------------------------------------------------------------------
#--[Class Declaration]----------------------------------------------------------
#-------------------------------------------------------------------------------

unit class Gnome::Gio::T-ioenums:auth<github:MARTIMM>:api<2>;
#-------------------------------------------------------------------------------
#--[Enumerations]---------------------------------------------------------------
#-------------------------------------------------------------------------------
enum GBusType is export <
  G_BUS_TYPE_STARTER G_BUS_TYPE_NONE G_BUS_TYPE_SYSTEM G_BUS_TYPE_SESSION 
>;

enum GConverterResult is export <
  G_CONVERTER_ERROR G_CONVERTER_CONVERTED G_CONVERTER_FINISHED G_CONVERTER_FLUSHED 
>;

enum GCredentialsType is export <
  G_CREDENTIALS_TYPE_INVALID G_CREDENTIALS_TYPE_LINUX_UCRED G_CREDENTIALS_TYPE_FREEBSD_CMSGCRED G_CREDENTIALS_TYPE_OPENBSD_SOCKPEERCRED G_CREDENTIALS_TYPE_SOLARIS_UCRED G_CREDENTIALS_TYPE_NETBSD_UNPCBID G_CREDENTIALS_TYPE_APPLE_XUCRED G_CREDENTIALS_TYPE_WIN32_PID 
>;

enum GDBusError is export <
  G_DBUS_ERROR_FAILED G_DBUS_ERROR_NO_MEMORY G_DBUS_ERROR_SERVICE_UNKNOWN G_DBUS_ERROR_NAME_HAS_NO_OWNER G_DBUS_ERROR_NO_REPLY G_DBUS_ERROR_IO_ERROR G_DBUS_ERROR_BAD_ADDRESS G_DBUS_ERROR_NOT_SUPPORTED G_DBUS_ERROR_LIMITS_EXCEEDED G_DBUS_ERROR_ACCESS_DENIED G_DBUS_ERROR_AUTH_FAILED G_DBUS_ERROR_NO_SERVER G_DBUS_ERROR_TIMEOUT G_DBUS_ERROR_NO_NETWORK G_DBUS_ERROR_ADDRESS_IN_USE G_DBUS_ERROR_DISCONNECTED G_DBUS_ERROR_INVALID_ARGS G_DBUS_ERROR_FILE_NOT_FOUND G_DBUS_ERROR_FILE_EXISTS G_DBUS_ERROR_UNKNOWN_METHOD G_DBUS_ERROR_TIMED_OUT G_DBUS_ERROR_MATCH_RULE_NOT_FOUND G_DBUS_ERROR_MATCH_RULE_INVALID G_DBUS_ERROR_SPAWN_EXEC_FAILED G_DBUS_ERROR_SPAWN_FORK_FAILED G_DBUS_ERROR_SPAWN_CHILD_EXITED G_DBUS_ERROR_SPAWN_CHILD_SIGNALED G_DBUS_ERROR_SPAWN_FAILED G_DBUS_ERROR_SPAWN_SETUP_FAILED G_DBUS_ERROR_SPAWN_CONFIG_INVALID G_DBUS_ERROR_SPAWN_SERVICE_INVALID G_DBUS_ERROR_SPAWN_SERVICE_NOT_FOUND G_DBUS_ERROR_SPAWN_PERMISSIONS_INVALID G_DBUS_ERROR_SPAWN_FILE_INVALID G_DBUS_ERROR_SPAWN_NO_MEMORY G_DBUS_ERROR_UNIX_PROCESS_ID_UNKNOWN G_DBUS_ERROR_INVALID_SIGNATURE G_DBUS_ERROR_INVALID_FILE_CONTENT G_DBUS_ERROR_SELINUX_SECURITY_CONTEXT_UNKNOWN G_DBUS_ERROR_ADT_AUDIT_DATA_UNKNOWN G_DBUS_ERROR_OBJECT_PATH_IN_USE G_DBUS_ERROR_UNKNOWN_OBJECT G_DBUS_ERROR_UNKNOWN_INTERFACE G_DBUS_ERROR_UNKNOWN_PROPERTY G_DBUS_ERROR_PROPERTY_READ_ONLY 
>;

enum GDBusMessageByteOrder is export <
  G_DBUS_MESSAGE_BYTE_ORDER_BIG_ENDIAN G_DBUS_MESSAGE_BYTE_ORDER_LITTLE_ENDIAN 
>;

enum GDBusMessageHeaderField is export <
  G_DBUS_MESSAGE_HEADER_FIELD_INVALID G_DBUS_MESSAGE_HEADER_FIELD_PATH G_DBUS_MESSAGE_HEADER_FIELD_INTERFACE G_DBUS_MESSAGE_HEADER_FIELD_MEMBER G_DBUS_MESSAGE_HEADER_FIELD_ERROR_NAME G_DBUS_MESSAGE_HEADER_FIELD_REPLY_SERIAL G_DBUS_MESSAGE_HEADER_FIELD_DESTINATION G_DBUS_MESSAGE_HEADER_FIELD_SENDER G_DBUS_MESSAGE_HEADER_FIELD_SIGNATURE G_DBUS_MESSAGE_HEADER_FIELD_NUM_UNIX_FDS 
>;

enum GDBusMessageType is export <
  G_DBUS_MESSAGE_TYPE_INVALID G_DBUS_MESSAGE_TYPE_METHOD_CALL G_DBUS_MESSAGE_TYPE_METHOD_RETURN G_DBUS_MESSAGE_TYPE_ERROR G_DBUS_MESSAGE_TYPE_SIGNAL 
>;

enum GDataStreamByteOrder is export <
  G_DATA_STREAM_BYTE_ORDER_BIG_ENDIAN G_DATA_STREAM_BYTE_ORDER_LITTLE_ENDIAN G_DATA_STREAM_BYTE_ORDER_HOST_ENDIAN 
>;

enum GDataStreamNewlineType is export <
  G_DATA_STREAM_NEWLINE_TYPE_LF G_DATA_STREAM_NEWLINE_TYPE_CR G_DATA_STREAM_NEWLINE_TYPE_CR_LF G_DATA_STREAM_NEWLINE_TYPE_ANY 
>;

enum GDriveStartStopType is export <
  G_DRIVE_START_STOP_TYPE_UNKNOWN G_DRIVE_START_STOP_TYPE_SHUTDOWN G_DRIVE_START_STOP_TYPE_NETWORK G_DRIVE_START_STOP_TYPE_MULTIDISK G_DRIVE_START_STOP_TYPE_PASSWORD 
>;

enum GEmblemOrigin is export <
  G_EMBLEM_ORIGIN_UNKNOWN G_EMBLEM_ORIGIN_DEVICE G_EMBLEM_ORIGIN_LIVEMETADATA G_EMBLEM_ORIGIN_TAG 
>;

enum GFileAttributeStatus is export <
  G_FILE_ATTRIBUTE_STATUS_UNSET G_FILE_ATTRIBUTE_STATUS_SET G_FILE_ATTRIBUTE_STATUS_ERROR_SETTING 
>;

enum GFileAttributeType is export <
  G_FILE_ATTRIBUTE_TYPE_INVALID G_FILE_ATTRIBUTE_TYPE_STRING G_FILE_ATTRIBUTE_TYPE_BYTE_STRING G_FILE_ATTRIBUTE_TYPE_BOOLEAN G_FILE_ATTRIBUTE_TYPE_UINT32 G_FILE_ATTRIBUTE_TYPE_INT32 G_FILE_ATTRIBUTE_TYPE_UINT64 G_FILE_ATTRIBUTE_TYPE_INT64 G_FILE_ATTRIBUTE_TYPE_OBJECT G_FILE_ATTRIBUTE_TYPE_STRINGV 
>;

enum GFileMonitorEvent is export <
  G_FILE_MONITOR_EVENT_CHANGED G_FILE_MONITOR_EVENT_CHANGES_DONE_HINT G_FILE_MONITOR_EVENT_DELETED G_FILE_MONITOR_EVENT_CREATED G_FILE_MONITOR_EVENT_ATTRIBUTE_CHANGED G_FILE_MONITOR_EVENT_PRE_UNMOUNT G_FILE_MONITOR_EVENT_UNMOUNTED G_FILE_MONITOR_EVENT_MOVED G_FILE_MONITOR_EVENT_RENAMED G_FILE_MONITOR_EVENT_MOVED_IN G_FILE_MONITOR_EVENT_MOVED_OUT 
>;

enum GFileType is export <
  G_FILE_TYPE_UNKNOWN G_FILE_TYPE_REGULAR G_FILE_TYPE_DIRECTORY G_FILE_TYPE_SYMBOLIC_LINK G_FILE_TYPE_SPECIAL G_FILE_TYPE_SHORTCUT G_FILE_TYPE_MOUNTABLE 
>;

enum GFilesystemPreviewType is export <
  G_FILESYSTEM_PREVIEW_TYPE_IF_ALWAYS G_FILESYSTEM_PREVIEW_TYPE_IF_LOCAL G_FILESYSTEM_PREVIEW_TYPE_NEVER 
>;

enum GIOErrorEnum is export <
  G_IO_ERROR_FAILED G_IO_ERROR_NOT_FOUND G_IO_ERROR_EXISTS G_IO_ERROR_IS_DIRECTORY G_IO_ERROR_NOT_DIRECTORY G_IO_ERROR_NOT_EMPTY G_IO_ERROR_NOT_REGULAR_FILE G_IO_ERROR_NOT_SYMBOLIC_LINK G_IO_ERROR_NOT_MOUNTABLE_FILE G_IO_ERROR_FILENAME_TOO_LONG G_IO_ERROR_INVALID_FILENAME G_IO_ERROR_TOO_MANY_LINKS G_IO_ERROR_NO_SPACE G_IO_ERROR_INVALID_ARGUMENT G_IO_ERROR_PERMISSION_DENIED G_IO_ERROR_NOT_SUPPORTED G_IO_ERROR_NOT_MOUNTED G_IO_ERROR_ALREADY_MOUNTED G_IO_ERROR_CLOSED G_IO_ERROR_CANCELLED G_IO_ERROR_PENDING G_IO_ERROR_READ_ONLY G_IO_ERROR_CANT_CREATE_BACKUP G_IO_ERROR_WRONG_ETAG G_IO_ERROR_TIMED_OUT G_IO_ERROR_WOULD_RECURSE G_IO_ERROR_BUSY G_IO_ERROR_WOULD_BLOCK G_IO_ERROR_HOST_NOT_FOUND G_IO_ERROR_WOULD_MERGE G_IO_ERROR_FAILED_HANDLED G_IO_ERROR_TOO_MANY_OPEN_FILES G_IO_ERROR_NOT_INITIALIZED G_IO_ERROR_ADDRESS_IN_USE G_IO_ERROR_PARTIAL_INPUT G_IO_ERROR_INVALID_DATA G_IO_ERROR_DBUS_ERROR G_IO_ERROR_HOST_UNREACHABLE G_IO_ERROR_NETWORK_UNREACHABLE G_IO_ERROR_CONNECTION_REFUSED G_IO_ERROR_PROXY_FAILED G_IO_ERROR_PROXY_AUTH_FAILED G_IO_ERROR_PROXY_NEED_AUTH G_IO_ERROR_PROXY_NOT_ALLOWED G_IO_ERROR_BROKEN_PIPE G_IO_ERROR_CONNECTION_CLOSED G_IO_ERROR_NOT_CONNECTED G_IO_ERROR_MESSAGE_TOO_LARGE G_IO_ERROR_NO_SUCH_DEVICE 
>;

enum GIOModuleScopeFlags is export <
  G_IO_MODULE_SCOPE_NONE G_IO_MODULE_SCOPE_BLOCK_DUPLICATES 
>;

enum GMemoryMonitorWarningLevel is export <
  G_MEMORY_MONITOR_WARNING_LEVEL_LOW G_MEMORY_MONITOR_WARNING_LEVEL_MEDIUM G_MEMORY_MONITOR_WARNING_LEVEL_CRITICAL 
>;

enum GMountOperationResult is export <
  G_MOUNT_OPERATION_HANDLED G_MOUNT_OPERATION_ABORTED G_MOUNT_OPERATION_UNHANDLED 
>;

enum GNetworkConnectivity is export <
  G_NETWORK_CONNECTIVITY_LOCAL G_NETWORK_CONNECTIVITY_LIMITED G_NETWORK_CONNECTIVITY_PORTAL G_NETWORK_CONNECTIVITY_FULL 
>;

enum GNotificationPriority is export <
  G_NOTIFICATION_PRIORITY_NORMAL G_NOTIFICATION_PRIORITY_LOW G_NOTIFICATION_PRIORITY_HIGH G_NOTIFICATION_PRIORITY_URGENT 
>;

enum GPasswordSave is export <
  G_PASSWORD_SAVE_NEVER G_PASSWORD_SAVE_FOR_SESSION G_PASSWORD_SAVE_PERMANENTLY 
>;

enum GPollableReturn is export <
  G_POLLABLE_RETURN_FAILED G_POLLABLE_RETURN_OK G_POLLABLE_RETURN_WOULD_BLOCK 
>;

enum GResolverError is export <
  G_RESOLVER_ERROR_NOT_FOUND G_RESOLVER_ERROR_TEMPORARY_FAILURE G_RESOLVER_ERROR_INTERNAL 
>;

enum GResolverRecordType is export <
  G_RESOLVER_RECORD_SRV G_RESOLVER_RECORD_MX G_RESOLVER_RECORD_TXT G_RESOLVER_RECORD_SOA G_RESOLVER_RECORD_NS 
>;

enum GResourceError is export <
  G_RESOURCE_ERROR_NOT_FOUND G_RESOURCE_ERROR_INTERNAL 
>;

enum GSocketClientEvent is export <
  G_SOCKET_CLIENT_RESOLVING G_SOCKET_CLIENT_RESOLVED G_SOCKET_CLIENT_CONNECTING G_SOCKET_CLIENT_CONNECTED G_SOCKET_CLIENT_PROXY_NEGOTIATING G_SOCKET_CLIENT_PROXY_NEGOTIATED G_SOCKET_CLIENT_TLS_HANDSHAKING G_SOCKET_CLIENT_TLS_HANDSHAKED G_SOCKET_CLIENT_COMPLETE 
>;

enum GSocketFamily is export <
  G_SOCKET_FAMILY_INVALID G_SOCKET_FAMILY_UNIX G_SOCKET_FAMILY_IPV4 G_SOCKET_FAMILY_IPV6 
>;

enum GSocketListenerEvent is export <
  G_SOCKET_LISTENER_BINDING G_SOCKET_LISTENER_BOUND G_SOCKET_LISTENER_LISTENING G_SOCKET_LISTENER_LISTENED 
>;

enum GSocketProtocol is export <
  G_SOCKET_PROTOCOL_UNKNOWN G_SOCKET_PROTOCOL_DEFAULT G_SOCKET_PROTOCOL_TCP G_SOCKET_PROTOCOL_UDP G_SOCKET_PROTOCOL_SCTP 
>;

enum GSocketType is export <
  G_SOCKET_TYPE_INVALID G_SOCKET_TYPE_STREAM G_SOCKET_TYPE_DATAGRAM G_SOCKET_TYPE_SEQPACKET 
>;

enum GTlsAuthenticationMode is export <
  G_TLS_AUTHENTICATION_NONE G_TLS_AUTHENTICATION_REQUESTED G_TLS_AUTHENTICATION_REQUIRED 
>;

enum GTlsCertificateRequestFlags is export <
  G_TLS_CERTIFICATE_REQUEST_NONE 
>;

enum GTlsChannelBindingError is export <
  G_TLS_CHANNEL_BINDING_ERROR_NOT_IMPLEMENTED G_TLS_CHANNEL_BINDING_ERROR_INVALID_STATE G_TLS_CHANNEL_BINDING_ERROR_NOT_AVAILABLE G_TLS_CHANNEL_BINDING_ERROR_NOT_SUPPORTED G_TLS_CHANNEL_BINDING_ERROR_GENERAL_ERROR 
>;

enum GTlsChannelBindingType is export <
  G_TLS_CHANNEL_BINDING_TLS_UNIQUE G_TLS_CHANNEL_BINDING_TLS_SERVER_END_POINT G_TLS_CHANNEL_BINDING_TLS_EXPORTER 
>;

enum GTlsDatabaseLookupFlags is export <
  G_TLS_DATABASE_LOOKUP_NONE G_TLS_DATABASE_LOOKUP_KEYPAIR 
>;

enum GTlsError is export <
  G_TLS_ERROR_UNAVAILABLE G_TLS_ERROR_MISC G_TLS_ERROR_BAD_CERTIFICATE G_TLS_ERROR_NOT_TLS G_TLS_ERROR_HANDSHAKE G_TLS_ERROR_CERTIFICATE_REQUIRED G_TLS_ERROR_EOF G_TLS_ERROR_INAPPROPRIATE_FALLBACK G_TLS_ERROR_BAD_CERTIFICATE_PASSWORD 
>;

enum GTlsInteractionResult is export <
  G_TLS_INTERACTION_UNHANDLED G_TLS_INTERACTION_HANDLED G_TLS_INTERACTION_FAILED 
>;

enum GTlsProtocolVersion is export <
  G_TLS_PROTOCOL_VERSION_UNKNOWN G_TLS_PROTOCOL_VERSION_SSL_3_0 G_TLS_PROTOCOL_VERSION_TLS_1_0 G_TLS_PROTOCOL_VERSION_TLS_1_1 G_TLS_PROTOCOL_VERSION_TLS_1_2 G_TLS_PROTOCOL_VERSION_TLS_1_3 G_TLS_PROTOCOL_VERSION_DTLS_1_0 G_TLS_PROTOCOL_VERSION_DTLS_1_2 
>;

enum GTlsRehandshakeMode is export <
  G_TLS_REHANDSHAKE_NEVER G_TLS_REHANDSHAKE_SAFELY G_TLS_REHANDSHAKE_UNSAFELY 
>;

enum GUnixSocketAddressType is export <
  G_UNIX_SOCKET_ADDRESS_INVALID G_UNIX_SOCKET_ADDRESS_ANONYMOUS G_UNIX_SOCKET_ADDRESS_PATH G_UNIX_SOCKET_ADDRESS_ABSTRACT G_UNIX_SOCKET_ADDRESS_ABSTRACT_PADDED 
>;

enum GZlibCompressorFormat is export <
  G_ZLIB_COMPRESSOR_FORMAT_ZLIB G_ZLIB_COMPRESSOR_FORMAT_GZIP G_ZLIB_COMPRESSOR_FORMAT_RAW 
>;

#-------------------------------------------------------------------------------
#--[Bitfields]------------------------------------------------------------------
#-------------------------------------------------------------------------------
enum GAppInfoCreateFlags is export (
  :G_APP_INFO_CREATE_NONE(0), :G_APP_INFO_CREATE_NEEDS_TERMINAL(1), :G_APP_INFO_CREATE_SUPPORTS_URIS(2), :G_APP_INFO_CREATE_SUPPORTS_STARTUP_NOTIFICATION(4)
);

enum GApplicationFlags is export (
  :G_APPLICATION_FLAGS_NONE(0), :G_APPLICATION_DEFAULT_FLAGS(0), :G_APPLICATION_IS_SERVICE(1), :G_APPLICATION_IS_LAUNCHER(2), :G_APPLICATION_HANDLES_OPEN(4), :G_APPLICATION_HANDLES_COMMAND_LINE(8), :G_APPLICATION_SEND_ENVIRONMENT(16), :G_APPLICATION_NON_UNIQUE(32), :G_APPLICATION_CAN_OVERRIDE_APP_ID(64), :G_APPLICATION_ALLOW_REPLACEMENT(128), :G_APPLICATION_REPLACE(256)
);

enum GAskPasswordFlags is export (
  :G_ASK_PASSWORD_NEED_PASSWORD(1), :G_ASK_PASSWORD_NEED_USERNAME(2), :G_ASK_PASSWORD_NEED_DOMAIN(4), :G_ASK_PASSWORD_SAVING_SUPPORTED(8), :G_ASK_PASSWORD_ANONYMOUS_SUPPORTED(16), :G_ASK_PASSWORD_TCRYPT(32)
);

enum GBusNameOwnerFlags is export (
  :G_BUS_NAME_OWNER_FLAGS_NONE(0), :G_BUS_NAME_OWNER_FLAGS_ALLOW_REPLACEMENT(1), :G_BUS_NAME_OWNER_FLAGS_REPLACE(2), :G_BUS_NAME_OWNER_FLAGS_DO_NOT_QUEUE(4)
);

enum GBusNameWatcherFlags is export (
  :G_BUS_NAME_WATCHER_FLAGS_NONE(0), :G_BUS_NAME_WATCHER_FLAGS_AUTO_START(1)
);

enum GConverterFlags is export (
  :G_CONVERTER_NO_FLAGS(0), :G_CONVERTER_INPUT_AT_END(1), :G_CONVERTER_FLUSH(2)
);

enum GDBusCallFlags is export (
  :G_DBUS_CALL_FLAGS_NONE(0), :G_DBUS_CALL_FLAGS_NO_AUTO_START(1), :G_DBUS_CALL_FLAGS_ALLOW_INTERACTIVE_AUTHORIZATION(2)
);

enum GDBusCapabilityFlags is export (
  :G_DBUS_CAPABILITY_FLAGS_NONE(0), :G_DBUS_CAPABILITY_FLAGS_UNIX_FD_PASSING(1)
);

enum GDBusConnectionFlags is export (
  :G_DBUS_CONNECTION_FLAGS_NONE(0), :G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_CLIENT(1), :G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_SERVER(2), :G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_ALLOW_ANONYMOUS(4), :G_DBUS_CONNECTION_FLAGS_MESSAGE_BUS_CONNECTION(8), :G_DBUS_CONNECTION_FLAGS_DELAY_MESSAGE_PROCESSING(16), :G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_REQUIRE_SAME_USER(32), :G_DBUS_CONNECTION_FLAGS_CROSS_NAMESPACE(64)
);

enum GDBusInterfaceSkeletonFlags is export (
  :G_DBUS_INTERFACE_SKELETON_FLAGS_NONE(0), :G_DBUS_INTERFACE_SKELETON_FLAGS_HANDLE_METHOD_INVOCATIONS_IN_THREAD(1)
);

enum GDBusMessageFlags is export (
  :G_DBUS_MESSAGE_FLAGS_NONE(0), :G_DBUS_MESSAGE_FLAGS_NO_REPLY_EXPECTED(1), :G_DBUS_MESSAGE_FLAGS_NO_AUTO_START(2), :G_DBUS_MESSAGE_FLAGS_ALLOW_INTERACTIVE_AUTHORIZATION(4)
);

enum GDBusObjectManagerClientFlags is export (
  :G_DBUS_OBJECT_MANAGER_CLIENT_FLAGS_NONE(0), :G_DBUS_OBJECT_MANAGER_CLIENT_FLAGS_DO_NOT_AUTO_START(1)
);

enum GDBusPropertyInfoFlags is export (
  :G_DBUS_PROPERTY_INFO_FLAGS_NONE(0), :G_DBUS_PROPERTY_INFO_FLAGS_READABLE(1), :G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE(2)
);

enum GDBusProxyFlags is export (
  :G_DBUS_PROXY_FLAGS_NONE(0), :G_DBUS_PROXY_FLAGS_DO_NOT_LOAD_PROPERTIES(1), :G_DBUS_PROXY_FLAGS_DO_NOT_CONNECT_SIGNALS(2), :G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START(4), :G_DBUS_PROXY_FLAGS_GET_INVALIDATED_PROPERTIES(8), :G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START_AT_CONSTRUCTION(16), :G_DBUS_PROXY_FLAGS_NO_MATCH_RULE(32)
);

enum GDBusSendMessageFlags is export (
  :G_DBUS_SEND_MESSAGE_FLAGS_NONE(0), :G_DBUS_SEND_MESSAGE_FLAGS_PRESERVE_SERIAL(1)
);

enum GDBusServerFlags is export (
  :G_DBUS_SERVER_FLAGS_NONE(0), :G_DBUS_SERVER_FLAGS_RUN_IN_THREAD(1), :G_DBUS_SERVER_FLAGS_AUTHENTICATION_ALLOW_ANONYMOUS(2), :G_DBUS_SERVER_FLAGS_AUTHENTICATION_REQUIRE_SAME_USER(4)
);

enum GDBusSignalFlags is export (
  :G_DBUS_SIGNAL_FLAGS_NONE(0), :G_DBUS_SIGNAL_FLAGS_NO_MATCH_RULE(1), :G_DBUS_SIGNAL_FLAGS_MATCH_ARG0_NAMESPACE(2), :G_DBUS_SIGNAL_FLAGS_MATCH_ARG0_PATH(4)
);

enum GDBusSubtreeFlags is export (
  :G_DBUS_SUBTREE_FLAGS_NONE(0), :G_DBUS_SUBTREE_FLAGS_DISPATCH_TO_UNENUMERATED_NODES(1)
);

enum GDriveStartFlags is export (
  :G_DRIVE_START_NONE(0)
);

enum GFileAttributeInfoFlags is export (
  :G_FILE_ATTRIBUTE_INFO_NONE(0), :G_FILE_ATTRIBUTE_INFO_COPY_WITH_FILE(1), :G_FILE_ATTRIBUTE_INFO_COPY_WHEN_MOVED(2)
);

enum GFileCopyFlags is export (
  :G_FILE_COPY_NONE(0), :G_FILE_COPY_OVERWRITE(1), :G_FILE_COPY_BACKUP(2), :G_FILE_COPY_NOFOLLOW_SYMLINKS(4), :G_FILE_COPY_ALL_METADATA(8), :G_FILE_COPY_NO_FALLBACK_FOR_MOVE(16), :G_FILE_COPY_TARGET_DEFAULT_PERMS(32)
);

enum GFileCreateFlags is export (
  :G_FILE_CREATE_NONE(0), :G_FILE_CREATE_PRIVATE(1), :G_FILE_CREATE_REPLACE_DESTINATION(2)
);

enum GFileMeasureFlags is export (
  :G_FILE_MEASURE_NONE(0), :G_FILE_MEASURE_REPORT_ANY_ERROR(2), :G_FILE_MEASURE_APPARENT_SIZE(4), :G_FILE_MEASURE_NO_XDEV(8)
);

enum GFileMonitorFlags is export (
  :G_FILE_MONITOR_NONE(0), :G_FILE_MONITOR_WATCH_MOUNTS(1), :G_FILE_MONITOR_SEND_MOVED(2), :G_FILE_MONITOR_WATCH_HARD_LINKS(4), :G_FILE_MONITOR_WATCH_MOVES(8)
);

enum GFileQueryInfoFlags is export (
  :G_FILE_QUERY_INFO_NONE(0), :G_FILE_QUERY_INFO_NOFOLLOW_SYMLINKS(1)
);

enum GIOStreamSpliceFlags is export (
  :G_IO_STREAM_SPLICE_NONE(0), :G_IO_STREAM_SPLICE_CLOSE_STREAM1(1), :G_IO_STREAM_SPLICE_CLOSE_STREAM2(2), :G_IO_STREAM_SPLICE_WAIT_FOR_BOTH(4)
);

enum GMountMountFlags is export (
  :G_MOUNT_MOUNT_NONE(0)
);

enum GMountUnmountFlags is export (
  :G_MOUNT_UNMOUNT_NONE(0), :G_MOUNT_UNMOUNT_FORCE(1)
);

enum GOutputStreamSpliceFlags is export (
  :G_OUTPUT_STREAM_SPLICE_NONE(0), :G_OUTPUT_STREAM_SPLICE_CLOSE_SOURCE(1), :G_OUTPUT_STREAM_SPLICE_CLOSE_TARGET(2)
);

enum GResourceFlags is export (
  :G_RESOURCE_FLAGS_NONE(0), :G_RESOURCE_FLAGS_COMPRESSED(1)
);

enum GResourceLookupFlags is export (
  :G_RESOURCE_LOOKUP_FLAGS_NONE(0)
);

enum GSocketMsgFlags is export (
  :G_SOCKET_MSG_NONE(0), :G_SOCKET_MSG_OOB(1), :G_SOCKET_MSG_PEEK(2), :G_SOCKET_MSG_DONTROUTE(4)
);

enum GSubprocessFlags is export (
  :G_SUBPROCESS_FLAGS_NONE(0), :G_SUBPROCESS_FLAGS_STDIN_PIPE(1), :G_SUBPROCESS_FLAGS_STDIN_INHERIT(2), :G_SUBPROCESS_FLAGS_STDOUT_PIPE(4), :G_SUBPROCESS_FLAGS_STDOUT_SILENCE(8), :G_SUBPROCESS_FLAGS_STDERR_PIPE(16), :G_SUBPROCESS_FLAGS_STDERR_SILENCE(32), :G_SUBPROCESS_FLAGS_STDERR_MERGE(64), :G_SUBPROCESS_FLAGS_INHERIT_FDS(128), :G_SUBPROCESS_FLAGS_SEARCH_PATH_FROM_ENVP(256)
);

enum GTestDBusFlags is export (
  :G_TEST_DBUS_NONE(0)
);

enum GTlsCertificateFlags is export (
  :G_TLS_CERTIFICATE_NO_FLAGS(0), :G_TLS_CERTIFICATE_UNKNOWN_CA(1), :G_TLS_CERTIFICATE_BAD_IDENTITY(2), :G_TLS_CERTIFICATE_NOT_ACTIVATED(4), :G_TLS_CERTIFICATE_EXPIRED(8), :G_TLS_CERTIFICATE_REVOKED(16), :G_TLS_CERTIFICATE_INSECURE(32), :G_TLS_CERTIFICATE_GENERIC_ERROR(64), :G_TLS_CERTIFICATE_VALIDATE_ALL(127)
);

enum GTlsDatabaseVerifyFlags is export (
  :G_TLS_DATABASE_VERIFY_NONE(0)
);

enum GTlsPasswordFlags is export (
  :G_TLS_PASSWORD_NONE(0), :G_TLS_PASSWORD_RETRY(2), :G_TLS_PASSWORD_MANY_TRIES(4), :G_TLS_PASSWORD_FINAL_TRY(8), :G_TLS_PASSWORD_PKCS11_USER(16), :G_TLS_PASSWORD_PKCS11_SECURITY_OFFICER(32), :G_TLS_PASSWORD_PKCS11_CONTEXT_SPECIFIC(64)
);

